/*!
 * Knockout JavaScript library v3.5.0-pre
 * (c) The Knockout.js team - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(m){var y=this||(0,eval)("this"),w=y.document,L=y.navigator,v=y.jQuery,G=y.JSON;(function(m){"function"===typeof define&&define.amd?define(["exports","require"],m):"object"===typeof exports&&"object"===typeof module?m(module.exports||exports):m(y.ko={})})(function(M,N){function I(a,c){return null===a||typeof a in S?a===c:!1}function T(b,c){var d;return function(){d||(d=a.a.setTimeout(function(){d=m;b()},c))}}function U(b,c){var d;return function(){clearTimeout(d);d=a.a.setTimeout(b,c)}}function V(a,
c){c&&"change"!==c?"beforeChange"===c?this.Vb(a):this.Sa(a,c):this.Wb(a)}function W(a,c){null!==c&&c.s&&c.s()}function X(a,c){var d=this.Vc,e=d[r];e.W||(this.zb&&this.Za[c]?(d.Zb(c,a,this.Za[c]),this.Za[c]=null,--this.zb):e.C[c]||d.Zb(c,a,e.H?{ea:a}:d.Gc(a)),a.Ra&&a.Pc())}function J(b,c,d,e){a.f[b]={init:function(b,g,k,l,h){var p,n;a.u(function(){var k=g(),q=a.a.c(k),q=!d!==!q,C=!n;if(C||c||q!==p)C&&a.fa.ya()&&(n=a.a.Ka(a.h.childNodes(b),!0)),q?(C||a.h.qa(b,a.a.Ka(n)),a.Ha(e?e(h,k):h,b)):a.h.La(b),
p=q},null,{l:b});return{controlsDescendantBindings:!0}}};a.j.Ja[b]=!1;a.h.aa[b]=!0}var a="undefined"!==typeof M?M:{};a.b=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.J=function(a,c,d){a[c]=d};a.version="3.5.0-pre";a.b("version",a.version);a.options={deferUpdates:!1,useOnlyNativeEvents:!1};a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)f.call(b,c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=
b;return a}function e(b,c,d,h){var e=b[c].match(x)||[];a.a.A(d.match(x),function(b){a.a.Ga(e,b,h)});b[c]=e.join(" ")}var f=Object.prototype.hasOwnProperty,g={__proto__:[]}instanceof Array,k="function"===typeof Symbol,l={},h={};l[L&&/Firefox\/2/i.test(L.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];l.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(l,function(a,b){if(b.length)for(var c=0,d=b.length;c<d;c++)h[b[c]]=
a});var p={propertychange:!0},n=w&&function(){for(var a=3,b=w.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:m}(),x=/\S+/g,q;return{oc:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],A:function(a,b,c){if(a&&"function"==typeof a.forEach)a.forEach(b,c);else for(var d=0,h=a.length;d<h;d++)b.call(c,a[d],d,a)},B:function(a,b){if(a&&"function"==typeof a.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<
d;c++)if(a[c]===b)return c;return-1},bc:function(a,b,c){if(a&&"function"==typeof a.find)return a.find(b,c);for(var d=0,h=a.length;d<h;d++)if(b.call(c,a[d],d,a))return a[d];return m},Xa:function(b,c){var d=a.a.B(b,c);0<d?b.splice(d,1):0===d&&b.shift()},cc:function(b){b=b||[];var c=[];a.a.A(b,function(b){0>a.a.B(c,b)&&c.push(b)});return c},vb:function(a,b,c){if(a&&"function"==typeof a.map)return a.map(b,c);a=a||[];for(var d=[],h=0,e=a.length;h<e;h++)d.push(b.call(c,a[h],h));return d},Va:function(a,
b,c){if(a&&"function"==typeof a.filter)return a.filter(b,c);a=a||[];for(var d=[],h=0,e=a.length;h<e;h++)b.call(c,a[h],h)&&d.push(a[h]);return d},Wa:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);return a},Ga:function(b,c,d){var h=a.a.B(a.a.Ib(b),c);0>h?d&&b.push(c):d||b.splice(h,1)},wa:g,extend:c,setPrototypeOf:d,ob:g?d:c,K:b,za:function(a,b,c){if(!a)return a;var d={},h;for(h in a)f.call(a,h)&&(d[h]=b.call(c,a[h],h,a));return d},Cb:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},
Fb:function(b){b=a.a.ia(b);for(var c=(b[0]&&b[0].ownerDocument||w).createElement("div"),d=0,h=b.length;d<h;d++)c.appendChild(a.la(b[d]));return c},Ka:function(b,c){for(var d=0,h=b.length,e=[];d<h;d++){var f=b[d].cloneNode(!0);e.push(c?a.la(f):f)}return e},qa:function(b,c){a.a.Cb(b);if(c)for(var d=0,h=c.length;d<h;d++)b.appendChild(c[d])},Dc:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var h=d[0],e=h.parentNode,f=0,g=c.length;f<g;f++)e.insertBefore(c[f],h);f=0;for(g=d.length;f<g;f++)a.removeNode(d[f])}},
Na:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.splice(0,1);for(;1<a.length&&a[a.length-1].parentNode!==b;)a.length--;if(1<a.length){var c=a[0],d=a[a.length-1];for(a.length=0;c!==d;)a.push(c),c=c.nextSibling;a.push(d)}}return a},Fc:function(a,b){7>n?a.setAttribute("selected",b):a.selected=b},qb:function(a){return null===a||a===m?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Bd:function(a,b){a=a||"";return b.length>a.length?
!1:a.substring(0,b.length)===b},$c:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(1!==a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Bb:function(b){return a.a.$c(b,b.ownerDocument.documentElement)},$b:function(b){return!!a.a.bc(b,a.a.Bb)},L:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},fc:function(b){return a.onError?function(){try{return b.apply(this,
arguments)}catch(c){throw a.onError&&a.onError(c),c;}}:b},setTimeout:function(b,c){return setTimeout(a.a.fc(b),c)},lc:function(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},F:function(b,c,d){var h=a.a.fc(d);d=p[c];if(a.options.useOnlyNativeEvents||d||!v)if(d||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var e=function(a){h.call(b,a)},f="on"+c;b.attachEvent(f,e);a.a.O.Fa(b,function(){b.detachEvent(f,e)})}else throw Error("Browser doesn't support addEventListener or attachEvent");
else b.addEventListener(c,h,!1);else q||(q="function"==typeof v(b).on?"on":"bind"),v(b)[q](c,h)},tb:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var d;"input"===a.a.L(b)&&b.type&&"click"==c.toLowerCase()?(d=b.type,d="checkbox"==d||"radio"==d):d=!1;if(a.options.useOnlyNativeEvents||!v||d)if("function"==typeof w.createEvent)if("function"==typeof b.dispatchEvent)d=w.createEvent(h[c]||"HTMLEvents"),d.initEvent(c,!0,!0,y,0,0,0,0,0,!1,!1,!1,!1,0,b),
b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");else v(b).trigger(c)},c:function(b){return a.P(b)?b():b},Ib:function(b){return a.P(b)?b.D():b},sb:function(b,c,d){var h;c&&("object"===typeof b.classList?(h=b.classList[d?"add":"remove"],a.a.A(c.match(x),function(a){h.call(b.classList,a)})):"string"===typeof b.className.baseVal?
e(b.className,"baseVal",c,d):e(b,"className",c,d))},pb:function(b,c){var d=a.a.c(c);if(null===d||d===m)d="";var h=a.h.firstChild(b);!h||3!=h.nodeType||a.h.nextSibling(h)?a.h.qa(b,[b.ownerDocument.createTextNode(d)]):h.data=d;a.a.ed(b)},Ec:function(a,b){a.name=b;if(7>=n)try{a.mergeAttributes(w.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},ed:function(a){9<=n&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},ad:function(a){if(n){var b=a.style.width;a.style.width=
0;a.style.width=b}},wd:function(b,c){b=a.a.c(b);c=a.a.c(c);for(var d=[],h=b;h<=c;h++)d.push(h);return d},ia:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},jc:function(a){return k?Symbol(a):a},Ed:6===n,Fd:7===n,V:n,qc:function(b,c){for(var d=a.a.ia(b.getElementsByTagName("input")).concat(a.a.ia(b.getElementsByTagName("textarea"))),h="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},e=[],f=d.length-1;0<=f;f--)h(d[f])&&e.push(d[f]);return e},
ud:function(b){return"string"==typeof b&&(b=a.a.qb(b))?G&&G.parse?G.parse(b):(new Function("return "+b))():null},Ob:function(b,c,d){if(!G||!G.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return G.stringify(a.a.c(b),c,d)},vd:function(c,d,h){h=h||{};var e=h.params||{},f=h.includeFields||this.oc,g=c;if("object"==typeof c&&
"form"===a.a.L(c))for(var g=c.action,p=f.length-1;0<=p;p--)for(var n=a.a.qc(c,f[p]),k=n.length-1;0<=k;k--)e[n[k].name]=n[k].value;d=a.a.c(d);var q=w.createElement("form");q.style.display="none";q.action=g;q.method="post";for(var l in d)c=w.createElement("input"),c.type="hidden",c.name=l,c.value=a.a.Ob(a.a.c(d[l])),q.appendChild(c);b(e,function(a,b){var c=w.createElement("input");c.type="hidden";c.name=a;c.value=b;q.appendChild(c)});w.body.appendChild(q);h.submitter?h.submitter(q):q.submit();setTimeout(function(){q.parentNode.removeChild(q)},
0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.A);a.b("utils.arrayFirst",a.a.bc);a.b("utils.arrayFilter",a.a.Va);a.b("utils.arrayGetDistinctValues",a.a.cc);a.b("utils.arrayIndexOf",a.a.B);a.b("utils.arrayMap",a.a.vb);a.b("utils.arrayPushAll",a.a.Wa);a.b("utils.arrayRemoveItem",a.a.Xa);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.oc);a.b("utils.getFormFields",a.a.qc);a.b("utils.objectMap",a.a.za);a.b("utils.peekObservable",a.a.Ib);a.b("utils.postJson",a.a.vd);a.b("utils.parseJson",
a.a.ud);a.b("utils.registerEventHandler",a.a.F);a.b("utils.stringifyJson",a.a.Ob);a.b("utils.range",a.a.wd);a.b("utils.toggleDomNodeCssClass",a.a.sb);a.b("utils.triggerEvent",a.a.tb);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.K);a.b("utils.addOrRemoveItem",a.a.Ga);a.b("utils.setTextContent",a.a.pb);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;if(1===arguments.length)return function(){return c.apply(a,arguments)};var d=Array.prototype.slice.call(arguments,
1);return function(){var e=d.slice(0);e.push.apply(e,arguments);return c.apply(a,e)}});a.a.g=new function(){function a(b,g){var k=b[d];if(!k||"null"===k||!e[k]){if(!g)return m;k=b[d]="ko"+c++;e[k]={}}return e[k]}var c=0,d="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var e=a(c,!1);return e===m?m:e[d]},set:function(c,d,e){if(e!==m||a(c,!1)!==m)a(c,!0)[d]=e},clear:function(a){var b=a[d];return b?(delete e[b],a[d]=null,!0):!1},S:function(){return c++ +d}}};a.b("utils.domData",a.a.g);a.b("utils.domData.clear",
a.a.g.clear);a.a.O=new function(){function b(b,c){var e=a.a.g.get(b,d);e===m&&c&&(e=[],a.a.g.set(b,d,e));return e}function c(d){var e=b(d,!1);if(e)for(var e=e.slice(0),l=0;l<e.length;l++)e[l](d);a.a.g.clear(d);a.a.O.cleanExternalData(d);if(f[d.nodeType])for(e=d.firstChild;d=e;)e=d.nextSibling,8===d.nodeType&&c(d)}var d=a.a.g.S(),e={1:!0,8:!0,9:!0},f={1:!0,9:!0};return{Fa:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Cc:function(c,e){var f=b(c,!1);
f&&(a.a.Xa(f,e),0==f.length&&a.a.g.set(c,d,m))},la:function(a){if(e[a.nodeType]&&(c(a),f[a.nodeType]))for(var b=a.getElementsByTagName("*"),d,h=0;h<b.length;h++)if(c(d=b[h]),b[h]!==d)throw Error("ko.cleanNode: An already cleaned node was removed from the document");return a},removeNode:function(b){a.la(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){v&&"function"==typeof v.cleanData&&v.cleanData([a])}}};a.la=a.a.O.la;a.removeNode=a.a.O.removeNode;a.b("cleanNode",a.la);
a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.O);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.O.Fa);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.O.Cc);(function(){var b=[0,"",""],c=[1,"<table>","</table>"],d=[3,"<table><tbody><tr>","</tr></tbody></table>"],e=[1,"<select multiple='multiple'>","</select>"],f={thead:c,tbody:c,tfoot:c,tr:[2,"<table><tbody>","</tbody></table>"],td:d,th:d,option:e,optgroup:e},g=8>=a.a.V;a.a.pa=function(c,d){var h;if(v)if(v.parseHTML)h=v.parseHTML(c,
d)||[];else{if((h=v.clean([c],d))&&h[0]){for(var e=h[0];e.parentNode&&11!==e.parentNode.nodeType;)e=e.parentNode;e.parentNode&&e.parentNode.removeChild(e)}}else{(h=d)||(h=w);var e=h.parentWindow||h.defaultView||y,n=a.a.qb(c).toLowerCase(),x=h.createElement("div"),q;q=(n=n.match(/^<([a-z]+)[ >]/))&&f[n[1]]||b;n=q[0];q="ignored<div>"+q[1]+c+q[2]+"</div>";"function"==typeof e.innerShiv?x.appendChild(e.innerShiv(q)):(g&&h.appendChild(x),x.innerHTML=q,g&&x.parentNode.removeChild(x));for(;n--;)x=x.lastChild;
h=a.a.ia(x.lastChild.childNodes)}return h};a.a.sd=function(b,c){var d=a.a.pa(b,c);return d.length&&d[0].parentElement||a.a.Fb(d)};a.a.Mb=function(b,c){a.a.Cb(b);c=a.a.c(c);if(null!==c&&c!==m)if("string"!=typeof c&&(c=c.toString()),v)v(b).html(c);else for(var d=a.a.pa(c,b.ownerDocument),e=0;e<d.length;e++)b.appendChild(d[e])}})();a.b("utils.parseHtmlFragment",a.a.pa);a.b("utils.setHtml",a.a.Mb);a.X=function(){function b(c,e){if(c)if(8==c.nodeType){var f=a.X.yc(c.nodeValue);null!=f&&e.push({Zc:c,qd:f})}else if(1==
c.nodeType)for(var f=0,g=c.childNodes,k=g.length;f<k;f++)b(g[f],e)}var c={};return{Eb:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},Jc:function(a,b){var f=c[a];if(f===m)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return f.apply(null,
b||[]),!0}finally{delete c[a]}},Kc:function(c,e){var f=[];b(c,f);for(var g=0,k=f.length;g<k;g++){var l=f[g].Zc,h=[l];e&&a.a.Wa(h,e);a.X.Jc(f[g].qd,h);l.nodeValue="";l.parentNode&&l.parentNode.removeChild(l)}},yc:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.X);a.b("memoization.memoize",a.X.Eb);a.b("memoization.unmemoize",a.X.Jc);a.b("memoization.parseMemoText",a.X.yc);a.b("memoization.unmemoizeDomNodeAndDescendants",a.X.Kc);a.ja=function(){function b(){if(f)for(var b=
f,c=0,d;k<f;)if(d=e[k++]){if(k>b){if(5E3<=++c){k=f;a.a.lc(Error("'Too much recursion' after processing "+c+" task groups."));break}b=f}try{d()}catch(n){a.a.lc(n)}}}function c(){b();k=f=e.length=0}var d,e=[],f=0,g=1,k=0;y.MutationObserver?d=function(a){var b=w.createElement("div");(new MutationObserver(a)).observe(b,{attributes:!0});return function(){b.classList.toggle("foo")}}(c):d=w&&"onreadystatechange"in w.createElement("script")?function(a){var b=w.createElement("script");b.onreadystatechange=
function(){b.onreadystatechange=null;w.documentElement.removeChild(b);b=null;a()};w.documentElement.appendChild(b)}:function(a){setTimeout(a,0)};return{scheduler:d,nb:function(b){f||a.ja.scheduler(c);e[f++]=b;return g++},cancel:function(a){a=a-(g-f);a>=k&&a<f&&(e[a]=null)},resetForTesting:function(){var a=f-k;k=f=e.length=0;return a},zd:b}}();a.b("tasks",a.ja);a.b("tasks.schedule",a.ja.nb);a.b("tasks.runEarly",a.ja.zd);a.Ma={throttle:function(b,c){b.throttleEvaluation=c;var d=null;return a.N({read:b,
write:function(e){clearTimeout(d);d=a.a.setTimeout(function(){b(e)},c)}})},rateLimit:function(a,c){var d,e,f;"number"==typeof c?d=c:(d=c.timeout,e=c.method);a.ub=!1;f="notifyWhenChangesStop"==e?U:T;a.kb(function(a){return f(a,d)})},deferred:function(b,c){if(!0!==c)throw Error("The 'deferred' extender only accepts the value 'true', because it is not supported to turn deferral off once enabled.");b.ub||(b.ub=!0,b.kb(function(c){var e,f=!1;return function(){if(!f){a.ja.cancel(e);e=a.ja.nb(c);try{f=!0,
b.notifySubscribers(m,"dirty")}finally{f=!1}}}}))},notify:function(a,c){a.equalityComparer="always"==c?null:I}};var S={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.Ma);a.Hc=function(b,c,d){this.ea=b;this.wb=c;this.Yc=d;this.W=!1;a.J(this,"dispose",this.s)};a.Hc.prototype.s=function(){this.W=!0;this.Yc()};a.T=function(){a.a.ob(this,B);B.fb(this)};var B={fb:function(a){a.M={change:[]};a.Xb=1},subscribe:function(b,c,d){var e=this;d=d||"change";var f=new a.Hc(e,c?b.bind(c):b,function(){a.a.Xa(e.M[d],
f);e.Ta&&e.Ta(d)});e.Ia&&e.Ia(d);e.M[d]||(e.M[d]=[]);e.M[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";"change"===c&&this.Sb();if(this.cb(c)){var d="change"===c&&this.Nc||this.M[c].slice(0);try{a.o.dc();for(var e=0,f;f=d[e];++e)f.W||f.wb(b)}finally{a.o.end()}}},bb:function(){return this.Xb},jd:function(a){return this.bb()!==a},Sb:function(){++this.Xb},kb:function(b){var c=this,d=a.P(c),e,f,g,k;c.Sa||(c.Sa=c.notifySubscribers,c.notifySubscribers=V);var l=b(function(){c.Ra=!1;d&&
k===c&&(k=c.Tb?c.Tb():c());var a=f||c.hb(g,k);f=e=!1;a&&c.Sa(g=k)});c.Wb=function(a){c.Nc=c.M.change.slice(0);c.Ra=e=!0;k=a;l()};c.Vb=function(a){e||(g=a,c.Sa(a,"beforeChange"))};c.Pc=function(){c.hb(g,c.D(!0))&&(f=!0)}},cb:function(a){return this.M[a]&&this.M[a].length},gd:function(b){if(b)return this.M[b]&&this.M[b].length||0;var c=0;a.a.K(this.M,function(a,b){"dirty"!==a&&(c+=b.length)});return c},hb:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,c)},extend:function(b){var c=
this;b&&a.a.K(b,function(b,e){var f=a.Ma[b];"function"==typeof f&&(c=f(c,e)||c)});return c}};a.J(B,"init",B.fb);a.J(B,"subscribe",B.subscribe);a.J(B,"extend",B.extend);a.J(B,"getSubscriptionsCount",B.gd);a.a.wa&&a.a.setPrototypeOf(B,Function.prototype);a.T.fn=B;a.vc=function(a){return null!=a&&"function"==typeof a.subscribe&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.T);a.b("isSubscribable",a.vc);a.fa=a.o=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=
0;return{dc:b,end:c,Jb:function(b){if(e){if(!a.vc(b))throw Error("Only subscribable things can act as dependencies");e.wb.call(e.Uc,b,b.Oc||(b.Oc=++f))}},G:function(a,d,e){try{return b(),a.apply(d,e||[])}finally{c()}},ya:function(){if(e)return e.u.ya()},ab:function(){if(e)return e.u.ab()},ib:function(){if(e)return e.ib}}}();a.b("computedContext",a.fa);a.b("computedContext.getDependenciesCount",a.fa.ya);a.b("computedContext.getDependencies",a.fa.ab);a.b("computedContext.isInitial",a.fa.ib);a.b("computedContext.registerDependency",
a.fa.Jb);a.b("ignoreDependencies",a.Dd=a.o.G);var F=a.a.jc("_latestValue");a.da=function(b){function c(){if(0<arguments.length)return c.hb(c[F],arguments[0])&&(c.ta(),c[F]=arguments[0],c.sa()),this;a.o.Jb(c);return c[F]}c[F]=b;a.a.wa||a.a.extend(c,a.T.fn);a.T.fn.fb(c);a.a.ob(c,E);a.options.deferUpdates&&a.Ma.deferred(c,!0);return c};var E={equalityComparer:I,D:function(){return this[F]},sa:function(){this.notifySubscribers(this[F],"spectate");this.notifySubscribers(this[F])},ta:function(){this.notifySubscribers(this[F],
"beforeChange")}};a.a.wa&&a.a.setPrototypeOf(E,a.T.fn);var H=a.da.Ea="__ko_proto__";E[H]=a.da;a.P=function(b){if((b="function"==typeof b&&b[H])&&b!==a.da&&b!==a.u)throw Error("Invalid object that looks like an observable; possibly from another Knockout instance");return!!b};a.Oa=function(b){return"function"==typeof b&&(b[H]===a.da||b[H]===a.u&&b.sc)};a.b("observable",a.da);a.b("isObservable",a.P);a.b("isWriteableObservable",a.Oa);a.b("isWritableObservable",a.Oa);a.b("observable.fn",E);a.J(E,"peek",
E.D);a.J(E,"valueHasMutated",E.sa);a.J(E,"valueWillMutate",E.ta);a.Aa=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.da(b);a.a.ob(b,a.Aa.fn);return b.extend({trackArrayChanges:!0})};a.Aa.fn={remove:function(b){for(var c=this.D(),d=[],e="function"!=typeof b||a.P(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var g=c[f];if(e(g)){0===d.length&&this.ta();if(c[f]!==g)throw Error("Array modified during remove; cannot remove item");
d.push(g);c.splice(f,1);f--}}d.length&&this.sa();return d},removeAll:function(b){if(b===m){var c=this.D(),d=c.slice(0);this.ta();c.splice(0,c.length);this.sa();return d}return b?this.remove(function(c){return 0<=a.a.B(b,c)}):[]},destroy:function(b){var c=this.D(),d="function"!=typeof b||a.P(b)?function(a){return a===b}:b;this.ta();for(var e=c.length-1;0<=e;e--){var f=c[e];d(f)&&(f._destroy=!0)}this.sa()},destroyAll:function(b){return b===m?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=
a.a.B(b,c)}):[]},indexOf:function(b){var c=this();return a.a.B(c,b)},replace:function(a,c){var d=this.indexOf(a);0<=d&&(this.ta(),this.D()[d]=c,this.sa())},sorted:function(a){var c=this().slice(0);return a?c.sort(a):c.sort()},reversed:function(){return this().slice(0).reverse()}};a.a.wa&&a.a.setPrototypeOf(a.Aa.fn,a.da.fn);a.a.A("pop push reverse shift sort splice unshift".split(" "),function(b){a.Aa.fn[b]=function(){var a=this.D();this.ta();this.ec(a,b,arguments);var d=a[b].apply(a,arguments);this.sa();
return d===a?this:d}});a.a.A(["slice"],function(b){a.Aa.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.b("observableArray",a.Aa);a.Ma.trackArrayChanges=function(b,c){function d(){if(!e){e=!0;l=b.notifySubscribers;b.notifySubscribers=function(a,b){b&&"change"!==b||++k;return l.apply(this,arguments)};var c=[].concat(b.D()||[]);f=null;g=b.subscribe(function(d){d=[].concat(d||[]);if(b.cb("arrayChange")){var e;if(!f||1<k)f=a.a.yb(c,d,b.xb);e=f}c=d;f=null;k=0;e&&e.length&&b.notifySubscribers(e,
"arrayChange")})}}b.xb={};c&&"object"==typeof c&&a.a.extend(b.xb,c);b.xb.sparse=!0;if(!b.ec){var e=!1,f=null,g,k=0,l,h=b.Ia,p=b.Ta;b.Ia=function(a){h&&h.call(b,a);"arrayChange"===a&&d()};b.Ta=function(a){p&&p.call(b,a);"arrayChange"!==a||b.cb("arrayChange")||(l&&(b.notifySubscribers=l,l=m),g&&g.s(),g=null,e=!1)};b.ec=function(b,c,d){function h(a,b,c){return p[p.length]={status:a,value:b,index:c}}if(e&&!k){var p=[],g=b.length,l=d.length,m=0;switch(c){case "push":m=g;case "unshift":for(c=0;c<l;c++)h("added",
d[c],m+c);break;case "pop":m=g-1;case "shift":g&&h("deleted",b[m],m);break;case "splice":c=Math.min(Math.max(0,0>d[0]?g+d[0]:d[0]),g);for(var g=1===l?g:Math.min(c+(d[1]||0),g),l=c+l-2,m=Math.max(g,l),O=[],P=[],u=2;c<m;++c,++u)c<g&&P.push(h("deleted",b[c],c)),c<l&&O.push(h("added",d[u],c));a.a.pc(P,O);break;default:return}f=p}}}};var r=a.a.jc("_state");a.u=a.N=function(b,c,d){function e(){if(0<arguments.length){if("function"===typeof f)f.apply(g.$a,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");
return this}g.W||a.o.Jb(e);(g.ha||g.H&&e.eb())&&e.ga();return g.R}"object"===typeof b?d=b:(d=d||{},b&&(d.read=b));if("function"!=typeof d.read)throw Error("Pass a function that returns the value of the ko.computed");var f=d.write,g={R:m,na:!0,ha:!0,gb:!1,Pb:!1,W:!1,mb:!1,H:!1,Bc:d.read,$a:c||d.owner,l:d.disposeWhenNodeIsRemoved||d.l||null,xa:d.disposeWhen||d.xa,Ab:null,C:{},U:0,nc:null};e[r]=g;e.sc="function"===typeof f;a.a.wa||a.a.extend(e,a.T.fn);a.T.fn.fb(e);a.a.ob(e,A);d.pure?(g.mb=!0,g.H=!0,
a.a.extend(e,Z)):d.deferEvaluation&&a.a.extend(e,aa);a.options.deferUpdates&&a.Ma.deferred(e,!0);g.l&&(g.Pb=!0,g.l.nodeType||(g.l=null));g.H||d.deferEvaluation||e.ga();g.l&&e.ma()&&a.a.O.Fa(g.l,g.Ab=function(){e.s()});return e};var A={equalityComparer:I,ya:function(){return this[r].U},ab:function(){var b=[];a.a.K(this[r].C,function(a,d){b[d.Ca]=d.ea});return b},Zb:function(a,c,d){if(this[r].mb&&c===this)throw Error("A 'pure' computed must not be called recursively");this[r].C[a]=d;d.Ca=this[r].U++;
d.Da=c.bb()},eb:function(){var a,c,d=this[r].C;for(a in d)if(Object.prototype.hasOwnProperty.call(d,a)&&(c=d[a],this.Ba&&c.ea.Ra||c.ea.jd(c.Da)))return!0},pd:function(){this.Ba&&!this[r].gb&&this.Ba(!1)},ma:function(){var a=this[r];return a.ha||0<a.U},yd:function(){this.Ra?this[r].ha&&(this[r].na=!0):this.mc()},Gc:function(a){if(a.ub){var c=a.subscribe(this.pd,this,"dirty"),d=a.subscribe(this.yd,this);return{ea:a,s:function(){c.s();d.s()}}}return a.subscribe(this.mc,this)},mc:function(){var b=this,
c=b.throttleEvaluation;c&&0<=c?(clearTimeout(this[r].nc),this[r].nc=a.a.setTimeout(function(){b.ga(!0)},c)):b.Ba?b.Ba(!0):b.ga(!0)},ga:function(b){var c=this[r],d=c.xa,e=!1;if(!c.gb&&!c.W){if(c.l&&!a.a.Bb(c.l)||d&&d()){if(!c.Pb){this.s();return}}else c.Pb=!1;c.gb=!0;try{e=this.dd(b)}finally{c.gb=!1}return e}},dd:function(b){var c=this[r],d=!1,e=c.mb?m:!c.U,d={Vc:this,Za:c.C,zb:c.U};a.o.dc({Uc:d,wb:X,u:this,ib:e});c.C={};c.U=0;var f=this.cd(c,d);c.U?d=this.hb(c.R,f):(this.s(),d=!0);d&&(c.H?this.Sb():
this.notifySubscribers(c.R,"beforeChange"),c.R=f,this.notifySubscribers(c.R,"spectate"),!c.H&&b&&this.notifySubscribers(c.R));e&&this.notifySubscribers(c.R,"awake");return d},cd:function(b,c){try{var d=b.Bc;return b.$a?d.call(b.$a):d()}finally{a.o.end(),c.zb&&!b.H&&a.a.K(c.Za,W),b.na=b.ha=!1}},D:function(a){var c=this[r];(c.ha&&(a||!c.U)||c.H&&this.eb())&&this.ga();return c.R},kb:function(b){a.T.fn.kb.call(this,b);this.Tb=function(){this[r].na?this.ga():this[r].ha=!1;return this[r].R};this.Ba=function(a){this.Vb(this[r].R);
this[r].ha=!0;a&&(this[r].na=!0);this.Wb(this)}},s:function(){var b=this[r];!b.H&&b.C&&a.a.K(b.C,function(a,b){b.s&&b.s()});b.l&&b.Ab&&a.a.O.Cc(b.l,b.Ab);b.C=m;b.U=0;b.W=!0;b.na=!1;b.ha=!1;b.H=!1;b.l=m;b.xa=m;b.Bc=m;this.sc||(b.$a=m)}},Z={Ia:function(b){var c=this,d=c[r];if(!d.W&&d.H&&"change"==b){d.H=!1;if(d.na||c.eb())d.C=null,d.U=0,c.ga()&&c.Sb();else{var e=[];a.a.K(d.C,function(a,b){e[b.Ca]=a});a.a.A(e,function(a,b){var e=d.C[a],l=c.Gc(e.ea);l.Ca=b;l.Da=e.Da;d.C[a]=l})}d.W||c.notifySubscribers(d.R,
"awake")}},Ta:function(b){var c=this[r];c.W||"change"!=b||this.cb("change")||(a.a.K(c.C,function(a,b){b.s&&(c.C[a]={ea:b.ea,Ca:b.Ca,Da:b.Da},b.s())}),c.H=!0,this.notifySubscribers(m,"asleep"))},bb:function(){var b=this[r];b.H&&(b.na||this.eb())&&this.ga();return a.T.fn.bb.call(this)}},aa={Ia:function(a){"change"!=a&&"beforeChange"!=a||this.D()}};a.a.wa&&a.a.setPrototypeOf(A,a.T.fn);var Q=a.da.Ea;A[Q]=a.u;a.uc=function(b){return"function"==typeof b&&b[Q]===a.u};a.ld=function(b){return a.uc(b)&&b[r]&&
b[r].mb};a.b("computed",a.u);a.b("dependentObservable",a.u);a.b("isComputed",a.uc);a.b("isPureComputed",a.ld);a.b("computed.fn",A);a.J(A,"peek",A.D);a.J(A,"dispose",A.s);a.J(A,"isActive",A.ma);a.J(A,"getDependenciesCount",A.ya);a.J(A,"getDependencies",A.ab);a.Ac=function(b,c){if("function"===typeof b)return a.u(b,c,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.u(b,c)};a.b("pureComputed",a.Ac);(function(){function b(a,f,g){g=g||new d;a=f(a);if("object"!=typeof a||null===a||a===m||a instanceof RegExp||
a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var k=a instanceof Array?[]:{};g.save(a,k);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":k[c]=d;break;case "object":case "undefined":var p=g.get(d);k[c]=p!==m?p:b(d,f,g)}});return k}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.values=
[]}a.Ic=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.P(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Ic(b);return a.a.Ob(b,c,d)};d.prototype={constructor:d,save:function(b,c){var d=a.a.B(this.keys,b);0<=d?this.values[d]=c:(this.keys.push(b),this.values.push(c))},get:function(b){b=a.a.B(this.keys,b);return 0<=b?this.values[b]:m}}})();a.b("toJS",a.Ic);a.b("toJSON",a.toJSON);(function(){a.m=
{I:function(b){switch(a.a.L(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.g.get(b,a.f.options.Gb):7>=a.a.V?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.m.I(b.options[b.selectedIndex]):m;default:return b.value}},ua:function(b,c,d){switch(a.a.L(b)){case "option":switch(typeof c){case "string":a.a.g.set(b,a.f.options.Gb,m);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;
b.value=c;break;default:a.a.g.set(b,a.f.options.Gb,c),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof c?c:""}break;case "select":if(""===c||null===c)c=m;for(var e=-1,f=0,g=b.options.length,k;f<g;++f)if(k=a.m.I(b.options[f]),k==c||""===k&&c===m){e=f;break}if(d||0<=e||c===m&&1<b.size)b.selectedIndex=e,6===a.a.V&&a.a.setTimeout(function(){b.selectedIndex=e},0);break;default:if(null===c||c===m)c="";b.value=c}}}})();a.b("selectExtensions",a.m);a.b("selectExtensions.readValue",a.m.I);a.b("selectExtensions.writeValue",
a.m.ua);a.j=function(){function b(b){b=a.a.qb(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));b+="\n,";var c=[],d=b.match(e),n,k=[],q=0;if(1<d.length)for(var C=0,D;D=d[C];++C){var t=D.charCodeAt(0);if(44===t){if(0>=q){c.push(n&&k.length?{key:n,value:k.join("")}:{unknown:n||k.join("")});n=q=0;k=[];continue}}else if(58===t){if(!q&&!n&&1===k.length){n=k.pop();continue}}else if(47===t&&1<D.length&&(47===D.charCodeAt(1)||42===D.charCodeAt(1)))continue;else 47===t&&C&&1<D.length?(t=d[C-1].match(f))&&!g[t[0]]&&
(b=b.substr(b.indexOf(D)+1),d=b.match(e),C=-1,D="/"):40===t||123===t||91===t?++q:41===t||125===t||93===t?--q:n||k.length||34!==t&&39!==t||(D=D.slice(1,-1));k.push(D)}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:\\\\.|[^\"])*\"|'(?:\\\\.|[^'])*'|`(?:\\\\.|[^`])*`|/\\*(?:[^*]|\\*+[^*/])*\\*+/|//.*\n|/(?:\\\\.|[^/])+/w*|[^\\s:,/][^,\"'`{}()/:[\\]]*[^\\s,\"'`{}()/:[\\]]|[^\\s]","g"),f=/[\])"'A-Za-z0-9_$]+$/,g={"in":1,"return":1,
"typeof":1},k={};return{Ja:[],ra:k,Hb:b,lb:function(e,h){function f(b,h){var e;if(!C){var l=a.getBindingHandler(b);if(l&&l.preprocess&&!(h=l.preprocess(h,b,f)))return;if(l=k[b])e=h,0<=a.a.B(c,e)?e=!1:(l=e.match(d),e=null===l?!1:l[1]?"Object("+l[1]+")"+l[2]:e),l=e;l&&g.push("'"+("string"==typeof k[b]?k[b]:b)+"':function(_z){"+e+"=_z}")}q&&(h="function(){return "+h+" }");n.push("'"+b+"':"+h)}h=h||{};var n=[],g=[],q=h.valueAccessors,C=h.bindingParams,D="string"===typeof e?b(e):e;a.a.A(D,function(a){f(a.key||
a.unknown,a.value)});g.length&&f("_ko_property_writers","{"+g.join(",")+" }");return n.join(",")},od:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},Qa:function(b,c,d,e,f){if(b&&a.P(b))!a.Oa(b)||f&&b.D()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.j);a.b("expressionRewriting.bindingRewriteValidators",a.j.Ja);a.b("expressionRewriting.parseObjectLiteral",a.j.Hb);a.b("expressionRewriting.preProcessBindings",a.j.lb);a.b("expressionRewriting._twoWayBindings",
a.j.ra);a.b("jsonExpressionRewriting",a.j);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.j.lb);(function(){function b(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&k.test(f?a.text:a.nodeValue)}function d(a,d){for(var e=a,f=1,q=[];e=e.nextSibling;){if(c(e)&&(f--,0===f))return q;q.push(e);b(e)&&f++}if(!d)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,b){var c=d(a,b);return c?0<c.length?c[c.length-
1].nextSibling:a.nextSibling:null}var f=w&&"\x3c!--test--\x3e"===w.createComment("test").text,g=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,k=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,l={ul:!0,ol:!0};a.h={aa:{},childNodes:function(a){return b(a)?d(a):a.childNodes},La:function(c){if(b(c)){c=a.h.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Cb(c)},qa:function(c,d){if(b(c)){a.h.La(c);for(var e=c.nextSibling,f=0,q=d.length;f<q;f++)e.parentNode.insertBefore(d[f],
e)}else a.a.qa(c,d)},zc:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},tc:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.h.zc(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||c(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));return a.nextSibling&&c(a.nextSibling)?null:a.nextSibling},hd:b,Cd:function(a){return(a=
(f?a.text:a.nodeValue).match(g))?a[1]:null},xc:function(d){if(l[a.a.L(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var n;n=f.firstChild;var g=null;if(n){do if(g)g.push(n);else if(b(n)){var q=e(n,!0);q?n=q:g=[n]}else c(n)&&(g=[n]);while(n=n.nextSibling)}if(n=g)for(g=f.nextSibling,q=0;q<n.length;q++)g?d.insertBefore(n[q],g):d.appendChild(n[q])}while(f=f.nextSibling)}}}}})();a.b("virtualElements",a.h);a.b("virtualElements.allowedBindings",a.h.aa);a.b("virtualElements.emptyNode",a.h.La);a.b("virtualElements.insertAfter",
a.h.tc);a.b("virtualElements.prepend",a.h.zc);a.b("virtualElements.setDomNodeChildren",a.h.qa);(function(){a.ca=function(){this.Tc={}};a.a.extend(a.ca.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.i.getComponentNameForNode(b);case 8:return a.h.hd(b);default:return!1}},getBindings:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,c,b):null;return a.i.Yb(d,b,c,!1)},getBindingAccessors:function(b,c){var d=this.getBindingsString(b,
c),d=d?this.parseBindingsString(d,c,b,{valueAccessors:!0}):null;return a.i.Yb(d,b,c,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.h.Cd(b);default:return null}},parseBindingsString:function(b,c,d,e){try{var f=this.Tc,g=b+(e&&e.valueAccessors||""),k;if(!(k=f[g])){var l,h="with($context){with($data||{}){return{"+a.j.lb(b,e)+"}}}";l=new Function("$context","$element",h);k=f[g]=l}return k(c,d)}catch(p){throw p.message="Unable to parse bindings.\nBindings value: "+
b+"\nMessage: "+p.message,p;}}});a.ca.instance=new a.ca})();a.b("bindingProvider",a.ca);(function(){function b(a){return function(){return a}}function c(a){return a()}function d(b){return a.a.za(a.o.G(b),function(a,c){return function(){return b()[c]}})}function e(c,e,h){return"function"===typeof c?d(c.bind(null,e,h)):a.a.za(c,b)}function f(a,b){return d(this.getBindings.bind(this,a,b))}function g(b,c){var d=a.h.firstChild(c);if(d){var e,h=a.ca.instance,f=h.preprocessNode;if(f){for(;e=d;)d=a.h.nextSibling(e),
f.call(h,e);d=a.h.firstChild(c)}for(;e=d;)d=a.h.nextSibling(e),k(b,e)}}function k(b,c){var d=!0,e=1===c.nodeType;e&&a.h.xc(c);if(e||a.ca.instance.nodeHasBindings(c))d=h(c,null,b).shouldBindDescendants;d&&!n[a.a.L(c)]&&g(b,c)}function l(b){var c=[],d={},e=[];a.a.K(b,function Y(h){if(!d[h]){var f=a.getBindingHandler(h);f&&(f.after&&(e.push(h),a.a.A(f.after,function(c){if(b[c]){if(-1!==a.a.B(e,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+e.join(", "));
Y(c)}}),e.length--),c.push({key:h,rc:f}));d[h]=!0}});return c}function h(b,d,e){var h=a.a.g.get(b,x);if(!d){if(h)throw Error("You cannot apply bindings multiple times to the same element.");a.a.g.set(b,x,{context:e});e.$&&e.$.Lc(b)}var g;if(d&&"function"!==typeof d)g=d;else{var n=a.ca.instance,k=n.getBindingAccessors||f,p=a.N(function(){(g=d?d(e,b):k.call(n,b,e))&&e.$&&e.$();return g},null,{l:b});g&&p.ma()||(p=null)}var u;if(g){var z=function(){return a.a.za(p?p():g,c)},r=p?function(a){return function(){return c(p()[a])}}:
function(a){return g[a]};z.get=function(a){return g[a]&&c(r(a))};z.has=function(a){return a in g};h=l(g);a.a.A(h,function(c){var d=c.rc.init,h=c.rc.update,f=c.key;if(8===b.nodeType&&!a.h.aa[f])throw Error("The binding '"+f+"' cannot be used with virtual elements");try{"function"==typeof d&&a.o.G(function(){var a=d(b,r(f),z,e.$data,e);if(a&&a.controlsDescendantBindings){if(u!==m)throw Error("Multiple bindings ("+u+" and "+f+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");
u=f}}),"function"==typeof h&&a.N(function(){h(b,r(f),z,e.$data,e)},null,{l:b})}catch(n){throw n.message='Unable to process binding "'+f+": "+g[f]+'"\nMessage: '+n.message,n;}})}return{shouldBindDescendants:u===m}}function p(b,c){return b&&b instanceof a.ba?b:new a.ba(b,m,m,c)}a.f={};var n={script:!0,textarea:!0,template:!0};a.getBindingHandler=function(b){return a.f[b]};a.ba=function(b,c,d,e,h){function f(){var h=k?b():b,g=a.a.c(h);c?(c.$&&c.$(),a.a.extend(n,c),n.$=l):(n.$parents=[],n.$root=g,n.ko=
a);n.$rawData=h;n.$data=g;d&&(n[d]=g);e&&e(n,c,g);return n.$data}function g(){return p&&!a.a.$b(p)}var n=this,k="function"==typeof b&&!a.P(b),p,l;h&&h.exportDependencies?f():(l=a.N(f,null,{xa:g,l:!0}),l.ma()&&(n.$=l,l.equalityComparer=null,p=[],l.Lc=function(b){p.push(b);a.a.O.Fa(b,function(b){a.a.Xa(p,b);p.length||(l.s(),n.$=l=m)})}))};a.ba.prototype.createChildContext=function(b,c,d,e){return new a.ba(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);
a.$parents.unshift(a.$parent);d&&d(a)},e)};a.ba.prototype.extend=function(b){return new a.ba(this.$||this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};a.ba.prototype.ic=function(a,b){return this.createChildContext(a,b,null,{exportDependencies:!0})};var x=a.a.g.S();a.Ad=function(b){return(b=a.a.g.get(b,x))&&b.context};a.Ua=function(b,c,d){1===b.nodeType&&a.h.xc(b);return h(b,c,p(d))};a.Rc=function(b,c,d){d=p(d);return a.Ua(b,e(c,d,b),d)};a.Ha=function(a,
b){1!==b.nodeType&&8!==b.nodeType||g(p(a),b)};a.ac=function(a,b,c){!v&&y.jQuery&&(v=y.jQuery);if(!b){if(b=y.document.body,!b)throw Error("ko.applyBindings: could not find window.document.body; has the document been loaded?");}else if(1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");k(p(a,c),b)};a.hc=function(b){return!b||1!==b.nodeType&&8!==b.nodeType?m:a.Ad(b)};a.Xc=function(b){return(b=a.hc(b))?b.$data:
m};a.b("bindingHandlers",a.f);a.b("applyBindings",a.ac);a.b("applyBindingsToDescendants",a.Ha);a.b("applyBindingAccessorsToNode",a.Ua);a.b("applyBindingsToNode",a.Rc);a.b("contextFor",a.hc);a.b("dataFor",a.Xc)})();(function(b){function c(c,e){var h=Object.prototype.hasOwnProperty.call(f,c)?f[c]:b,p;h?h.subscribe(e):(h=f[c]=new a.T,h.subscribe(e),d(c,function(b,d){var e=!(!d||!d.synchronous);g[c]={definition:b,md:e};delete f[c];p||e?h.notifySubscribers(b):a.ja.nb(function(){h.notifySubscribers(b)})}),
p=!0)}function d(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,c)}):b(null,null)})}function e(c,d,h,f){f||(f=a.i.loaders.slice(0));var g=f.shift();if(g){var x=g[c];if(x){var q=!1;if(x.apply(g,d.concat(function(a){q?h(null):null!==a?h(a):e(c,d,h,f)}))!==b&&(q=!0,!g.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,h,f)}else h(null)}var f={},g={};a.i={get:function(d,
e){var h=Object.prototype.hasOwnProperty.call(g,d)?g[d]:b;h?h.md?a.o.G(function(){e(h.definition)}):a.ja.nb(function(){e(h.definition)}):c(d,e)},fd:function(){debugger;return g},gc:function(a){delete g[a]},Ub:e};a.i.loaders=[];a.b("components",a.i);a.b("components.get",a.i.get);a.b("components.getAllLoaded",a.i.fd);a.b("components.clearCachedDefinition",a.i.gc)})();(function(){function b(b,c,d,e){function g(){0===--D&&e(k)}var k={},D=2,t=d.template;d=d.viewModel;t?f(c,t,function(c){a.i.Ub("loadTemplate",
[b,c],function(a){k.template=a;g()})}):g();d?f(c,d,function(c){a.i.Ub("loadViewModel",[b,c],function(a){k[l]=a;g()})}):g()}function c(a,b,d){if("function"===typeof b)d(function(a){return new b(a)});else if("function"===typeof b[l])d(b[l]);else if("instance"in b){var e=b.instance;d(function(){return e})}else"viewModel"in b?c(a,b.viewModel,d):a("Unknown viewModel value: "+b)}function d(b){switch(a.a.L(b)){case "script":return a.a.pa(b.text);case "textarea":return a.a.pa(b.value);case "template":if(e(b.content))return a.a.Ka(b.content.childNodes)}return a.a.Ka(b.childNodes)}
function e(a){return y.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType}function f(a,b,c){"string"===typeof b.require?N||y.require?(N||y.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function g(a){return function(b){throw Error("Component '"+a+"': "+b);}}var k={};a.i.register=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.i.jb(b))throw Error("Component "+b+" is already registered");k[b]=c};a.i.jb=function(a){return Object.prototype.hasOwnProperty.call(k,
a)};a.i.unregister=function(b){delete k[b];a.i.gc(b)};a.i.kc={getConfig:function(b,c){c(a.i.jb(b)?k[b]:null)},loadComponent:function(a,c,d){var e=g(a);f(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,c,f){b=g(b);if("string"===typeof c)f(a.a.pa(c));else if(c instanceof Array)f(c);else if(e(c))f(a.a.ia(c.childNodes));else if(c.element)if(c=c.element,y.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)f(d(c));else if("string"===typeof c){var k=w.getElementById(c);k?f(d(k)):b("Cannot find element with ID "+
c)}else b("Unknown element type: "+c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,d){c(g(a),b,d)}};var l="createViewModel";a.b("components.register",a.i.register);a.b("components.isRegistered",a.i.jb);a.b("components.unregister",a.i.unregister);a.b("components.defaultLoader",a.i.kc);a.i.loaders.push(a.i.kc);a.i.Mc=k})();(function(){function b(b,e){var f=b.getAttribute("params");if(f){var f=c.parseBindingsString(f,e,b,{valueAccessors:!0,bindingParams:!0}),f=a.a.za(f,function(c){return a.u(c,
null,{l:b})}),g=a.a.za(f,function(c){var e=c.D();return c.ma()?a.u({read:function(){return a.a.c(c())},write:a.Oa(e)&&function(a){c()(a)},l:b}):e});Object.prototype.hasOwnProperty.call(g,"$raw")||(g.$raw=f);return g}return{$raw:{}}}a.i.getComponentNameForNode=function(b){var c=a.a.L(b);if(a.i.jb(c)&&(-1!=c.indexOf("-")||"[object HTMLUnknownElement]"==""+b||8>=a.a.V&&b.tagName===c))return c};a.i.Yb=function(c,e,f,g){if(1===e.nodeType){var k=a.i.getComponentNameForNode(e);if(k){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');
var l={name:k,params:b(e,f)};c.component=g?function(){return l}:l}}return c};var c=new a.ca;9>a.a.V&&(a.i.register=function(a){return function(b){return a.apply(this,arguments)}}(a.i.register),w.createDocumentFragment=function(b){return function(){var c=b(),f=a.i.Mc,g;for(g in f);return c}}(w.createDocumentFragment))})();(function(b){function c(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.Ka(c);a.h.qa(d,b)}function d(a,b,c,d){var e=a.createViewModel;return e?e.call(a,
d,{element:b,templateNodes:c}):d}var e=0;a.f.component={init:function(f,g,k,l,h){function p(){var a=n&&n.dispose;"function"===typeof a&&a.call(n);x=n=null}var n,x,q=a.a.ia(a.h.childNodes(f));a.a.O.Fa(f,p);a.u(function(){var k=a.a.c(g()),l,t;"string"===typeof k?l=k:(l=a.a.c(k.name),t=a.a.c(k.params));if(!l)throw Error("No component name specified");var m=x=++e;a.i.get(l,function(e){if(x===m){p();if(!e)throw Error("Unknown component '"+l+"'");c(l,e,f);var g=d(e,f,q,t);e=h.createChildContext(g,b,function(a){a.$component=
g;a.$componentTemplateNodes=q});n=g;a.Ha(e,f)}})},null,{l:f});return{controlsDescendantBindings:!0}}};a.h.aa.component=!0})();var R={"class":"className","for":"htmlFor"};a.f.attr={update:function(b,c){var d=a.a.c(c())||{};a.a.K(d,function(c,d){d=a.a.c(d);var g=!1===d||null===d||d===m;g&&b.removeAttribute(c);8>=a.a.V&&c in R?(c=R[c],g?b.removeAttribute(c):b[c]=d):g||b.setAttribute(c,d.toString());"name"===c&&a.a.Ec(b,g?"":d.toString())})}};(function(){a.f.checked={after:["value","attr"],init:function(b,
c,d){function e(){var e=b.checked,f=g();if(!a.fa.ib()&&(e||!l&&!a.fa.ya())){var h=a.o.G(c);if(p){var x=n?h.D():h,r=q;q=f;r!==f?e&&(a.a.Ga(x,f,!0),a.a.Ga(x,r,!1)):a.a.Ga(x,f,e);n&&a.Oa(h)&&h(x)}else k&&(f===m?f=e:e||(f=m)),a.j.Qa(h,d,"checked",f,!0)}}function f(){var d=a.a.c(c()),e=g();p?(b.checked=0<=a.a.B(d,e),q=e):b.checked=k&&e===m?!!d:g()===d}var g=a.Ac(function(){return d.has("checkedValue")?a.a.c(d.get("checkedValue")):d.has("value")?a.a.c(d.get("value")):x?b.value:m}),k="checkbox"==b.type,
l="radio"==b.type;if(k||l){var h=c(),p=k&&a.a.c(h)instanceof Array,n=!(p&&h.push&&h.splice),x=l||p,q=p?g():m;l&&!b.name&&a.f.uniqueName.init(b,function(){return!0});a.u(e,null,{l:b});a.a.F(b,"click",e);a.u(f,null,{l:b});h=m}}};a.j.ra.checked=!0;a.f.checkedValue={update:function(b,c){b.value=a.a.c(c())}}})();a.f["class"]={update:function(b,c){var d=a.a.qb(a.a.c(c()));a.a.sb(b,b.__ko__cssValue,!1);b.__ko__cssValue=d;a.a.sb(b,d,!0)}};a.f.css={update:function(b,c){var d=a.a.c(c());null!==d&&"object"==
typeof d?a.a.K(d,function(c,d){d=a.a.c(d);a.a.sb(b,c,d)}):a.f["class"].update(b,c)}};a.f.enable={update:function(b,c){var d=a.a.c(c());d&&b.disabled?b.removeAttribute("disabled"):d||b.disabled||(b.disabled=!0)}};a.f.disable={update:function(b,c){a.f.enable.update(b,function(){return!a.a.c(c())})}};a.f.event={init:function(b,c,d,e,f){var g=c()||{};a.a.K(g,function(g){"string"==typeof g&&a.a.F(b,g,function(b){var h,p=c()[g];if(p){try{var n=a.a.ia(arguments);e=f.$data;n.unshift(e);h=p.apply(e,n)}finally{!0!==
h&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(g+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.f.foreach={wc:function(b){return function(){var c=b(),d=a.a.Ib(c);if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.Y.Ea};a.a.c(c);return{foreach:d.data,as:d.as,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:d.afterRender,beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.Y.Ea}}},
init:function(b,c){return a.f.template.init(b,a.f.foreach.wc(c))},update:function(b,c,d,e,f){return a.f.template.update(b,a.f.foreach.wc(c),d,e,f)}};a.j.Ja.foreach=!1;a.h.aa.foreach=!0;a.f.hasfocus={init:function(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if("activeElement"in f){var h;try{h=f.activeElement}catch(g){h=f.body}e=h===b}f=c();a.j.Qa(f,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),g=e.bind(null,!1);a.a.F(b,"focus",
f);a.a.F(b,"focusin",f);a.a.F(b,"blur",g);a.a.F(b,"focusout",g)},update:function(b,c){var d=!!a.a.c(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===d||(d?b.focus():b.blur(),!d&&b.__ko_hasfocusLastValue&&b.ownerDocument.body.focus(),a.o.G(a.a.tb,null,[b,d?"focusin":"focusout"]))}};a.j.ra.hasfocus=!0;a.f.hasFocus=a.f.hasfocus;a.j.ra.hasFocus="hasfocus";a.f.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Mb(b,c())}};J("if");J("ifnot",!1,!0);J("with",!0,
!1,function(a,c){return a.ic(c)});a.f.let={init:function(b,c,d,e,f){c=f.extend(c);a.Ha(c,b);return{controlsDescendantBindings:!0}}};a.h.aa.let=!0;var K={};a.f.options={init:function(b){if("select"!==a.a.L(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,c,d){function e(){return a.a.Va(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?
a[b]:c}function g(c,e){if(C&&p)a.m.ua(b,a.a.c(d.get("value")),!0);else if(q.length){var f=0<=a.a.B(q,a.m.I(e[0]));a.a.Fc(e[0],f);C&&!f&&a.o.G(a.a.tb,null,[b,"change"])}}var k=b.multiple,l=0!=b.length&&k?b.scrollTop:null,h=a.a.c(c()),p=d.get("valueAllowUnset")&&d.has("value"),n=d.get("optionsIncludeDestroyed");c={};var x,q=[];p||(k?q=a.a.vb(e(),a.m.I):0<=b.selectedIndex&&q.push(a.m.I(b.options[b.selectedIndex])));h&&("undefined"==typeof h.length&&(h=[h]),x=a.a.Va(h,function(b){return n||b===m||null===
b||!a.a.c(b._destroy)}),d.has("optionsCaption")&&(h=a.a.c(d.get("optionsCaption")),null!==h&&h!==m&&x.unshift(K)));var C=!1;c.beforeRemove=function(a){b.removeChild(a)};h=g;d.has("optionsAfterRender")&&"function"==typeof d.get("optionsAfterRender")&&(h=function(b,c){g(0,c);a.o.G(d.get("optionsAfterRender"),null,[c[0],b!==K?b:m])});a.a.Lb(b,x,function(c,e,h){h.length&&(q=!p&&h[0].selected?[a.m.I(h[0])]:[],C=!0);e=b.ownerDocument.createElement("option");c===K?(a.a.pb(e,d.get("optionsCaption")),a.m.ua(e,
m)):(h=f(c,d.get("optionsValue"),c),a.m.ua(e,a.a.c(h)),c=f(c,d.get("optionsText"),h),a.a.pb(e,c));return[e]},c,h);a.o.G(function(){if(p)a.m.ua(b,a.a.c(d.get("value")),!0);else{var c;k?c=q.length&&e().length<q.length:c=q.length&&0<=b.selectedIndex?a.m.I(b.options[b.selectedIndex])!==q[0]:q.length||0<=b.selectedIndex;c&&a.a.tb(b,"change")}});a.a.ad(b);l&&20<Math.abs(l-b.scrollTop)&&(b.scrollTop=l)}};a.f.options.Gb=a.a.g.S();a.f.selectedOptions={after:["options","foreach"],init:function(b,c,d){a.a.F(b,
"change",function(){var e=c(),f=[];a.a.A(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.m.I(b))});a.j.Qa(e,d,"selectedOptions",f)})},update:function(b,c){if("select"!=a.a.L(b))throw Error("values binding applies only to SELECT elements");var d=a.a.c(c()),e=b.scrollTop;d&&"number"==typeof d.length&&a.a.A(b.getElementsByTagName("option"),function(b){var c=0<=a.a.B(d,a.m.I(b));b.selected!=c&&a.a.Fc(b,c)});b.scrollTop=e}};a.j.ra.selectedOptions=!0;a.f.style={update:function(b,c){var d=
a.a.c(c()||{});a.a.K(d,function(c,d){d=a.a.c(d);if(null===d||d===m||!1===d)d="";b.style[c]=d})}};a.f.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");a.a.F(b,"submit",function(a){var d,e=c();try{d=e.call(f.$data,b)}finally{!0!==d&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.f.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.pb(b,c())}};a.h.aa.text=!0;(function(){if(y&&
y.navigator){var b=function(a){if(a)return parseFloat(a[1])},c=y.navigator.userAgent,d,e,f,g;(d=y.opera&&y.opera.version&&parseInt(y.opera.version()))||b(c.match(/Chrome\/([^ ]+)/))||(e=b(c.match(/Version\/([^ ]+) Safari/)))||(f=b(c.match(/Firefox\/([^ ]+)/)))||(g=a.a.V||b(c.match(/MSIE ([^ ]+)/)))||(g=b(c.match(/rv:([^ )]+)/)))}if(8<=g&&10>g)var k=a.a.g.S(),l=a.a.g.S(),h=function(b){var c=this.activeElement;(c=c&&a.a.g.get(c,l))&&c(b)},p=function(b,c){var d=b.ownerDocument;a.a.g.get(d,k)||(a.a.g.set(d,
k,!0),a.a.F(d,"selectionchange",h));a.a.g.set(b,l,c)};a.f.textInput={init:function(b,c,h){function k(c,d){a.a.F(b,c,d)}function l(){var d=a.a.c(c());if(null===d||d===m)d="";y!==m&&d===y?a.a.setTimeout(l,4):b.value!==d&&(w=d,b.value=d)}function t(){v||(y=b.value,v=a.a.setTimeout(r,4))}function r(){clearTimeout(v);y=v=m;var d=b.value;w!==d&&(w=d,a.j.Qa(c(),h,"textInput",d))}var w=b.value,v,y,u=9==a.a.V?t:r;g&&k("keypress",r);11>g&&k("propertychange",function(a){"value"===a.propertyName&&u(a)});8==g&&
(k("keyup",r),k("keydown",r));p&&(p(b,u),k("dragend",t));(!g||9<=g)&&k("input",u);5>e&&"textarea"===a.a.L(b)?(k("keydown",t),k("paste",t),k("cut",t)):11>d?k("keydown",t):4>f&&(k("DOMAutoComplete",r),k("dragdrop",r),k("drop",r));k("change",r);k("blur",r);a.u(l,null,{l:b})}};a.j.ra.textInput=!0;a.f.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.f.uniqueName={init:function(b,c){if(c()){var d="ko_unique_"+ ++a.f.uniqueName.Wc;a.a.Ec(b,d)}}};a.f.uniqueName.Wc=0;a.f.using={init:function(b,
c,d,e,f){c=f.createChildContext(c);a.Ha(c,b);return{controlsDescendantBindings:!0}}};a.h.aa.using=!0;a.f.value={after:["options","foreach"],init:function(b,c,d){var e=a.a.L(b),f="input"==e;if(!f||"checkbox"!=b.type&&"radio"!=b.type){var g=["change"],k=d.get("valueUpdate"),l=!1,h=null;k&&("string"==typeof k&&(k=[k]),a.a.Wa(g,k),g=a.a.cc(g));var p=function(){h=null;l=!1;var e=c(),f=a.m.I(b);a.j.Qa(e,d,"value",f)};!a.a.V||!f||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||
-1!=a.a.B(g,"propertychange")||(a.a.F(b,"propertychange",function(){l=!0}),a.a.F(b,"focus",function(){l=!1}),a.a.F(b,"blur",function(){l&&p()}));a.a.A(g,function(c){var d=p;a.a.Bd(c,"after")&&(d=function(){h=a.m.I(b);a.a.setTimeout(p,0)},c=c.substring(5));a.a.F(b,c,d)});var n;n=f&&"file"==b.type?function(){var d=a.a.c(c());null===d||d===m||""===d?b.value="":a.o.G(p)}:function(){var f=a.a.c(c()),g=a.m.I(b);if(null!==h&&f===h)a.a.setTimeout(n,0);else if(f!==g||g===m)"select"===e?(g=d.get("valueAllowUnset"),
a.m.ua(b,f,g),g||f===a.m.I(b)||a.o.G(p)):a.m.ua(b,f)};a.u(n,null,{l:b})}else a.Ua(b,{checkedValue:c})},update:function(){}};a.j.ra.value=!0;a.f.visible={update:function(b,c){var d=a.a.c(c()),e="none"!=b.style.display;d&&!e?b.style.display="":!d&&e&&(b.style.display="none")}};a.f.hidden={update:function(b,c){a.f.visible.update(b,function(){return!a.a.c(c())})}};(function(b){a.f[b]={init:function(c,d,e,f,g){return a.f.event.init.call(this,c,function(){var a={};a[b]=d();return a},e,f,g)}}})("click");
a.Z=function(){};a.Z.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.Z.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.Z.prototype.makeTemplateSource=function(b,c){if("string"==typeof b){c=c||w;var d=c.getElementById(b);if(!d)throw Error("Cannot find template with ID "+b);return new a.w.v(d)}if(1==b.nodeType||8==b.nodeType)return new a.w.ka(b);throw Error("Unknown template type: "+b);};a.Z.prototype.renderTemplate=
function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d,e)};a.Z.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,c).data("isRewritten")};a.Z.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.b("templateEngine",a.Z);a.Qb=function(){function b(b,c,d,k){b=a.j.Hb(b);for(var l=a.j.Ja,h=0;h<b.length;h++){var p=b[h].key;if(Object.prototype.hasOwnProperty.call(l,
p)){var n=l[p];if("function"===typeof n){if(p=n(b[h].value))throw Error(p);}else if(!n)throw Error("This template engine does not support the '"+p+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.j.lb(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return k.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,
d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{bd:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.Qb.rd(b,c)},d)},rd:function(a,f){return a.replace(c,function(a,c,d,e,p){return b(p,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",f)})},Sc:function(b,c){return a.X.Eb(function(d,k){var l=d.nextSibling;l&&l.nodeName.toLowerCase()===c&&a.Ua(l,b,k)})}}}();a.b("__tr_ambtns",a.Qb.Sc);(function(){a.w={};a.w.v=function(b){if(this.v=b){var c=
a.a.L(b);this.rb="script"===c?1:"textarea"===c?2:"template"==c&&b.content&&11===b.content.nodeType?3:4}};a.w.v.prototype.text=function(){var b=1===this.rb?"text":2===this.rb?"value":"innerHTML";if(0==arguments.length)return this.v[b];var c=arguments[0];"innerHTML"===b?a.a.Mb(this.v,c):this.v[b]=c};var b=a.a.g.S()+"_";a.w.v.prototype.data=function(c){if(1===arguments.length)return a.a.g.get(this.v,b+c);a.a.g.set(this.v,b+c,arguments[1])};var c=a.a.g.S();a.w.v.prototype.nodes=function(){var b=this.v;
if(0==arguments.length){var e=a.a.g.get(b,c)||{},f=e.Ya||(3===this.rb?b.content:4===this.rb?b:m);if(!f||e.Qc)if(e=this.text())f=a.a.sd(e,b.ownerDocument),this.text(""),a.a.g.set(b,c,{Ya:f,Qc:!0});return f}a.a.g.set(b,c,{Ya:arguments[0]})};a.w.ka=function(a){this.v=a};a.w.ka.prototype=new a.w.v;a.w.ka.prototype.constructor=a.w.ka;a.w.ka.prototype.text=function(){if(0==arguments.length){var b=a.a.g.get(this.v,c)||{};b.Rb===m&&b.Ya&&(b.Rb=b.Ya.innerHTML);return b.Rb}a.a.g.set(this.v,c,{Rb:arguments[0]})};
a.b("templateSources",a.w);a.b("templateSources.domElement",a.w.v);a.b("templateSources.anonymousTemplate",a.w.ka)})();(function(){function b(b,c,d){var e;for(c=a.h.nextSibling(c);b&&(e=b)!==c;)b=a.h.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],g=e.parentNode,k=a.ca.instance,l=k.preprocessNode;if(l){b(e,f,function(a,b){var c=a.previousSibling,d=l.call(k,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):(c.push(e,f),a.a.Na(c,
g))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.ac(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.X.Kc(b,[d])});a.a.Na(c,g)}}function d(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,f,k,l){l=l||{};var m=(b&&d(b)||f||{}).ownerDocument,r=l.templateEngine||g;a.Qb.bd(f,r,m);f=r.renderTemplate(f,k,l,m);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");m=!1;switch(e){case "replaceChildren":a.h.qa(b,
f);m=!0;break;case "replaceNode":a.a.Dc(b,f);m=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+e);}m&&(c(f,k),l.afterRender&&a.o.G(l.afterRender,null,[f,k.$data]));return f}function f(b,c,d){return a.P(b)?b():"function"===typeof b?b(c,d):b}var g;a.Nb=function(b){if(b!=m&&!(b instanceof a.Z))throw Error("templateEngine must inherit from ko.templateEngine");g=b};a.Kb=function(b,c,k,l,q){k=k||{};if((k.templateEngine||g)==m)throw Error("Set a template engine before calling renderTemplate");
q=q||"replaceChildren";if(l){var r=d(l);return a.N(function(){var g=c&&c instanceof a.ba?c:new a.ba(c,null,null,null,{exportDependencies:!0}),m=f(b,g.$data,g),g=e(l,q,m,g,k);"replaceNode"==q&&(l=g,r=d(l))},null,{xa:function(){return!r||!a.a.Bb(r)},l:r&&"replaceNode"==q?r.parentNode:r})}return a.X.Eb(function(d){a.Kb(b,c,k,d,"replaceNode")})};a.xd=function(b,d,g,k,l){function r(a,b){c(b,t);g.afterRender&&g.afterRender(b,a);t=null}function v(a,c){t=l.createChildContext(a,g.as,function(a){a.$index=c});
var d=f(b,a,t);return e(k,"ignoreTargetNode",d,t,g)}var t;return a.N(function(){var b=a.a.c(d)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.Va(b,function(b){return g.includeDestroyed||b===m||null===b||!a.a.c(b._destroy)});a.o.G(a.a.Lb,null,[k,b,v,g,r])},null,{l:k})};var k=a.a.g.S(),l=a.a.g.S();a.f.template={init:function(b,c){var d=a.a.c(c());if("string"==typeof d||d.name)a.h.La(b);else{if("nodes"in d){d=d.nodes||[];if(a.P(d))throw Error('The "nodes" option must be a plain, non-observable array.');
var e=d[0]&&d[0].parentNode;e&&a.a.g.get(e,l)||(e=a.a.Fb(d),a.a.g.set(e,l,!0))}else d=a.h.childNodes(b),e=a.a.Fb(d);(new a.w.ka(b)).nodes(e)}return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var g=c();c=a.a.c(g);d=!0;e=null;"string"==typeof c?c={}:(g=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)));"foreach"in c?e=a.xd(g||b,d&&c.foreach||[],c,b,f):d?(f="data"in c?f.ic(c.data,c.as):f,e=a.Kb(g||b,f,c,b)):a.h.La(b);f=e;(c=a.a.g.get(b,k))&&"function"==typeof c.s&&
c.s();a.a.g.set(b,k,f&&f.ma()?f:m)}};a.j.Ja.template=function(b){b=a.j.Hb(b);return 1==b.length&&b[0].unknown||a.j.od(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.h.aa.template=!0})();a.b("setTemplateEngine",a.Nb);a.b("renderTemplate",a.Kb);a.a.pc=function(a,c,d){if(a.length&&c.length){var e,f,g,k,l;for(e=f=0;(!d||e<d)&&(k=a[f]);++f){for(g=0;l=c[g];++g)if(k.value===l.value){k.moved=l.index;l.moved=k.index;c.splice(g,1);e=g=0;break}e+=g}}};
a.a.yb=function(){function b(b,d,e,f,g){var k=Math.min,l=Math.max,h=[],p,n=b.length,m,q=d.length,r=q-n||1,v=n+q+1,t,w,y;for(p=0;p<=n;p++)for(w=t,h.push(t=[]),y=k(q,p+r),m=l(0,p-1);m<=y;m++)t[m]=m?p?b[p-1]===d[m-1]?w[m-1]:k(w[m]||v,t[m-1]||v)+1:m+1:p+1;k=[];l=[];r=[];p=n;for(m=q;p||m;)q=h[p][m]-1,m&&q===h[p][m-1]?l.push(k[k.length]={status:e,value:d[--m],index:m}):p&&q===h[p-1][m]?r.push(k[k.length]={status:f,value:b[--p],index:p}):(--m,--p,g.sparse||k.push({status:"retained",value:d[m]}));a.a.pc(r,
l,!g.dontLimitMoves&&10*n);return k.reverse()}return function(a,d,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.yb);(function(){function b(b,c,d,k,l){var h=[],p=a.N(function(){var m=c(d,l,a.a.Na(h,b))||[];0<h.length&&(a.a.Dc(h,m),k&&a.o.G(k,null,[d,m,l]));h.length=0;a.a.Wa(h,m)},null,{l:b,xa:function(){return!a.a.$b(h)}});return{oa:h,N:p.ma()?p:m}}var c=a.a.g.S(),d=
a.a.g.S();a.a.Lb=function(e,f,g,k,l){function h(b,c){u=r[c];y!==c&&(E[b]=u);u.Db(y++);a.a.Na(u.oa,e);w.push(u);B.push(u)}function p(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.A(c[d].oa,function(a){b(a,d,c[d].va)})}f=f||[];k=k||{};var n=a.a.g.get(e,c)===m,r=a.a.g.get(e,c)||[],q=a.a.vb(r,function(a){return a.va}),v=a.a.yb(q,f,k.dontLimitMoves),w=[],t=0,y=0,A=[],B=[];f=[];for(var E=[],q=[],u,z=0,F,G;F=v[z];z++)switch(G=F.moved,F.status){case "deleted":G===m&&(u=r[t],u.N&&(u.N.s(),u.N=m),a.a.Na(u.oa,
e).length&&(k.beforeRemove&&(w.push(u),B.push(u),u.va===d?u=null:f[z]=u),u&&A.push.apply(A,u.oa)));t++;break;case "retained":h(z,t++);break;case "added":G!==m?h(z,G):(u={va:F.value,Db:a.da(y++)},w.push(u),B.push(u),n||(q[z]=u))}a.a.g.set(e,c,w);p(k.beforeMove,E);a.a.A(A,k.beforeRemove?a.la:a.removeNode);for(var z=0,n=a.h.firstChild(e),H;u=B[z];z++){u.oa||a.a.extend(u,b(e,g,u.va,l,u.Db));for(t=0;v=u.oa[t];n=v.nextSibling,H=v,t++)v!==n&&a.h.tc(e,v,H);!u.kd&&l&&(l(u.va,u.oa,u.Db),u.kd=!0)}p(k.beforeRemove,
f);for(z=0;z<f.length;++z)f[z]&&(f[z].va=d);p(k.afterMove,E);p(k.afterAdd,q)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.Lb);a.Y=function(){this.allowTemplateRewriting=!1};a.Y.prototype=new a.Z;a.Y.prototype.constructor=a.Y;a.Y.prototype.renderTemplateSource=function(b,c,d,e){if(c=(9>a.a.V?0:b.nodes)?b.nodes():null)return a.a.ia(c.cloneNode(!0).childNodes);b=b.text();return a.a.pa(b,e)};a.Y.Ea=new a.Y;a.Nb(a.Y.Ea);a.b("nativeTemplateEngine",a.Y);(function(){a.Pa=function(){var a=this.nd=
function(){if(!v||!v.tmpl)return 0;try{if(0<=v.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f,g){g=g||w;f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var k=b.data("precompiled");k||(k=b.text()||"",k=v.template(null,"{{ko_with $item.koBindingContext}}"+k+"{{/ko_with}}"),b.data("precompiled",k));b=[e.$data];e=v.extend({koBindingContext:e},f.templateOptions);e=
v.tmpl(k,b,e);e.appendTo(g.createElement("div"));v.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){w.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(v.tmpl.tag.ko_code={open:"__.push($1 || '');"},v.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Pa.prototype=new a.Z;a.Pa.prototype.constructor=a.Pa;var b=new a.Pa;0<b.nd&&a.Nb(b);a.b("jqueryTmplTemplateEngine",a.Pa)})()})})();})();
